language: node_js
sudo: required
dist: xenial
addons:
  chrome:
    stable
  sonarcloud:
    organization: "wisdomb33r"
    token: ${SONAR_TOKEN}

node_js:
  - '14'

git:
  depth: false

before_script:
  - npm -v
  - node -v
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - npm run test-cc
  - sonar-scanner
